### ISSUE TITLE
Multer and Images

### ISSUE THREAD

**Issue by mwhite192** [mwhite192/groupomania#4]
@AccessiT3ch - Hey Conor!

When I was trying out multer, I kept getting a weird URL in by databased.  It would either say 'http://localhost:3000/images/undefined' or 'http://localhost:3000/images/C:\fakepath\D1171CD4-7011-4E1F-9AAC-653F0'.  I am not too sure why I am getting this.  I have saved the image to my desktop and even redid my multer-config.js file.  Any assistance here would be greatly appreicated.

**Comment by AccessiT3ch** [comment]
@mwhite192 Hmmm, here we need to find what is undefined is, where is the error coming from, front or back end?

**Comment by mwhite192** [comment]
@AccessiT3ch - there wasn’t an error. The urls posted were in the payload when creating a user. When I last attempted, I got an actual path however I the image want in the path.  The path I got was http://localhos3000/inages/ to this effect.

**Comment by mwhite192** [comment]
@AccessiT3ch - I finally got the images working!
