### ISSUE TITLE
Password Validation

### ISSUE THREAD

**Issue by mwhite192** [mwhite192/groupomania#5]
@AccessiT3ch - Hey again Conor!

As we know, I have quite a few form validation statements on the register and login page.  I have created validation for all field except password.  My question is, is there a statement I can write with the other validation statements that can validate the password without creating a confirm password field?  Or should I perform that validation on the backend?

**Comment by AccessiT3ch** [comment]
@mwhite192 password validation should be pretty straightforward, in this case you basically just need to make sure the input isnt empty, which we can do by setting `require="true"` on the input element. Actually checking the password will happen on the server by checking the hash thats saved in the db.

**Comment by mwhite192** [comment]
@AccessiT3ch - that’s good to know! I had a check to see if password was empty but I commented it out I think. Illl go back and add it.  I can check that off the list.
