### ISSUE TITLE
Redux Toolkit and Axios in Groupomania

### ISSUE THREAD

**Issue by mwhite192** [mwhite192/groupomania#6]
@AccessiT3ch - Hey for the last time today Conor :) !

I have to admit that I am really having trouble with Redux as it relates to my project.  I understand Redux and how it works.  I even understand Redux ToolKit.  What I am not understanding is how to go about connecting them to my project.  I tried creating a slice and it didn't work.  I tried creating an API slice.  That got me close to working, but the query I was using just kept getting rejected.  All the examples I see on the net and YouTube use Axios and I don't think we need to use Axios.  I am trying not to stress, but this is really putting me behind.  Any assistance at all you can give would really help.  Even if we can squeeze in another session this week would help also.  Please help :(

**Comment by AccessiT3ch** [comment]
Hey @mwhite192, we can definitely double up on sessions this week, shall we meet tomorrow? Correct, you don't need axios for this (axios is like fetch but a little more backwards compatible, so in this case fetch should be fine), so it sounds like there's a disconnect between your store and app.

Ill take a look tonight and see if i can figure what's going on :)

**Comment by mwhite192** [comment]
@AccessiT3ch  - tomorrow is perfect! I’m working half a day tomorrow so anytime after 12PM EST is perfect.  And thank you so much!  I haven’t recreated another slice.  I was hoping we could walk through it so I can see where my disconnect was cloning from.  Just wanted to give you a heads up. The store is configured though.

**Comment by AccessiT3ch** [comment]
@mwhite192 looking at what's been pushed it looks like the store doesn't have any reducers added to it https://github.com/mwhite192/groupomania/blob/master/src/App/store.js#L5

I'm also not seeing your slice, so maybe I'm missing something? Let's do 1p EST if that works for you, and we'll get this all sorted out for sure :)

**Comment by mwhite192** [comment]
@AccessiT3ch - 1PM EST works for me! I had added the reducers and even created a slice but deleted everything when thing s weren’t working. I was tfoing to go back to basics but decided to reach out for help instead.

**Comment by mwhite192** [comment]
@AccessiT3ch - Hey Conor!  Thanks for the extra session today!  That really helped!  I still haven'te created my slice, but I think I should be okay there since I have some reference.
